spring.application.name=UserAuthSystem

spring.datasource.url=jdbc:postgresql://manas.c9c6mio0snp7.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional (better logging)
spring.jpa.properties.hibernate.format_sql=true